name: mflow_service

on:
  push:
    branches:
      - main
      - production
      - staging

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: europe-west3
  GKE_CLUSTER: cluster-1
  GKE_ZONE: europe-west3-c
  DEPLOYMENT_NAME: production
  REPOSITORY: mlflow
  IMAGE: hosted-service
  DB_CONNECTION_NAME: opendatasets-349618:europe-west3:ml-flow-database
  DB_NAME: mlflow
  DB_USER: "mlflow-user"


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: Docker configuration
      run: |-
        gcloud beta auth configure-docker ${GAR_LOCATION}-docker.pkg.dev
    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}"
  
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        region ${GAR_LOCATION} 
        gcloud run deploy mlflow --image ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA} 
                                 --region ${GAR_LOCATION} 
                                 --add-cloudsql-instances ${DATABASE_CONNECTION_NAME}
                                 --set-env-vars INSTANCE_CONNECTION_NAME="${DATABASE_CONNECTION_NAME}"
                                 --set-env-vars INSTANCE_UNIX_SOCKET="/cloudsql/${DATABASE_CONNECTION_NAME}"
                                 --set-env-vars DB_NAME=${DB_NAME}
                                 --set-env-vars DB_USER="${DB_USER}
                                 --set-env-vars DB_PASS="${{ secrets.ML_FLOW_PASS }}"
                                 --set-env-vars GCP_PROJECT="${PROJECT_ID}"
                                 --set-env-vars DEFAULT_ARTIFACT_ROOT="gs://mlflow_cloud_storage_artifacts"
                                 --set-env-vars BACKEND_STORE_URI="postgresql://mlflow?unix_sock=/cloudsql/opendatasets-349618:europe-west3:ml-flow-database/.s.PGSQL.5432"
      # replacing the image name in the k8s template
      # kubectl kustomize edit set image ${GAR_LOCATION}-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG=${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}
      # kubectl kustomize build . | kubectl apply -f -
      # kubectl rollout status deployment/${DEPLOYMENT_NAME}
      # kubectl get services -o wide